version: '2'
services:
  healthcheck:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
    image: rancher/healthcheck:v0.3.3
    command: healthcheck --metadata-address 169.254.169.250
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  prometheus-rancher-exporter:
    tty: true
    stdin_open: true
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
    environment:
      - HIDE_SYS=false
    expose:
      - 9173
    volumes:
      - /etc/ssl:/etc/ssl:ro
    image: rancher/prometheus-rancher-exporter:latest
  rancherlb-prometheus-rancher-exporter:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 9173:9173/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
